{{- if .Values.realm.import }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-keycloak-realm
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
  dcs-realm.json: |-
{{ .Files.Get "files/dcs-realm.json" | indent 4 }}
{{- end }}
